spring:
  application:
    name: stock-average
  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

alphavantage:
  api-key: YOUR_API_KEY_HERE
  base-url: https://www.alphavantage.co/query

logging:
  level:
    com.stock: DEBUG
